PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../..

# create examples demonstrating the use of you package in subdirectories
# and list those subdirs in the TARGET variable.
TARGET = $(PKGNAME)-client

SRC_CC = rm_kb_client.cc

REQUIRES_LIBS = libc_be_mem libstdc++

include $(L4DIR)/mk/prog.mk


