PKGDIR ?= ../..
L4DIR	 ?= $(PKGDIR)/../..

TARGET = $(PKGNAME)

# list your .c or .cc files here
SRC_CC = log.cc

# list requirements of your program here
REQUIRES_LIBS = libc_be_mem libgfxbitmap libstdc++

include $(L4DIR)/mk/prog.mk
